version: '3'
 
tasks:
  build-debug:
    cmds:
      - dotnet build dojo.api.sln -c Debug
  run-debug:
    cmds:
      - cd dojo.api/bin/Debug && dotnet dojo.api.dll
    env:
      ASPNETCORE_ENVIRONMENT: Development
  build-release:
    cmds:
      - dotnet build dojo.api.sln -c Release
  run-release:
    cmds:
      - cd dojo.api/bin/Release
      - dotnet dojo.api.dll
    env:
      ASPNETCORE_ENVIRONMENT: Production
  publish:
    cmds:
      - dotnet publish dojo.api.sln -c Release
  build-image:
    cmds:
      - docker build -t manojbaishya/dojo.api -f Dockerfile .
  upload-image:
    cmds:
      - docker push manojbaishya/dojo.api
  deploy:
    cmds:
      - helm upgrade --install dojo-api dojo.api.charts/dojo-api --namespace=app
  uninstall:
    cmds:
      - helm uninstall dojo-api --namespace=app
  test:
    cmds:
      - dotnet test dojo.api.sln
  clean:
    cmds:
      - dotnet clean dojo.api.sln